#Coucou

NAME = phonebook
FLAGS = -Wall -Wextra -Werror -std=c++98
COMPIL = c++
SRC = main.cpp PhoneBook.class.cpp Contact.class.cpp

.PHONY : all test

all :
	$(COMPIL) $(FLAGS) $(SRC) -o $(NAME)

test :
	#./$(NAME)
	./test.sh